server:
  protocol: http
  http:
    port: 1663
job_queue:
  option: redis
  memory_job_queue:
    capacity: 100
  redis:
    key_prefix: automater
    min_idle_conns: 10
    pool_size: 10
worker_pool:
  workers:
  queue_capacity:
scheduler:
  storage_polling_interval: 1
  job_queue_polling_interval: 1
storage:
  option: redis
  redis:
    url: localhost
    key_prefix: automater
    min_idle_conns: 10
    pool_size: 10
timeout_unit: second
logging_format: text